{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default (include "generic-web-service-v2.fullname" .) .Values.configMap.name }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
{{- if .Values.extraConfigMaps }}
{{- range $name, $cm := .Values.extraConfigMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
data:
  {{- toYaml $cm.data | nindent 2 }}
{{- end }}
{{- end }}
