{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ default (include "generic-web-service-v2.fullname" .) .Values.externalSecret.target.name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ default (include "generic-web-service-v2.fullname" .) .Values.externalSecret.target.name }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
  data:
    {{- toYaml .Values.externalSecret.data | nindent 4 }}
{{- end }}
